### ISSUE TITLE
Upload failure

### ISSUE THREAD

**Issue by ohthetrees** [ctberthiaume/gdcp#10]
Uploading 150GB from AWS to GDrive.

```
03/26/2015 01:40:26 AM    INFO       gdcp                      : Uploaded 100.00%.  9556358352 bytes in 13m0.00s (11.44MB/s)
03/26/2015 01:40:26 AM    INFO       gdcp                      : Calculating MD5 checksum for sequences/khmer_qc/SA_s13_150m_1_2_201408280810/SA_s13_150m_1_2.fasta.gz.keep.abundfilt
03/26/2015 01:40:56 AM    INFO       gdcp                      : MD5 OK.  f86d7afe5eaaa89b8dca9ad00c2f83cc (local) == f86d7afe5eaaa89b8dca9ad00c2f83cc
03/26/2015 01:40:57 AM    INFO       gdcp                      : Uploading sequences/khmer_qc/SA_s13_150m_1_2_201408280810/SA_s13_150m_1_2.fasta.gz.keep.abundfilt.below, mimeType=application/octet-stream
03/26/2015 01:43:20 AM    INFO       gdcp                      : Uploaded 6.22% (3.67MB/s)
03/26/2015 01:43:51 AM    INFO       gdcp                      : Uploaded 12.43% (6.03MB/s)
03/26/2015 01:44:19 AM    INFO       gdcp                      : Uploaded 18.65% (7.79MB/s)
Traceback (most recent call last):
  File "/usr/local/bin/gdcp", line 1021, in <module>
    main()
  File "/usr/local/bin/gdcp", line 40, in main
    cli()
  File "/usr/local/bin/gdcp", line 912, in cli
    args.func(args)
  File "/usr/local/bin/gdcp", line 977, in cli_upload_file
    not args.no_checksum)
  File "/usr/local/bin/gdcp", line 594, in upload_folder
    drive, subdir, parent_id=folder_id, checksum=checksum)
  File "/usr/local/bin/gdcp", line 594, in upload_folder
    drive, subdir, parent_id=folder_id, checksum=checksum)
  File "/usr/local/bin/gdcp", line 589, in upload_folder
    drive, onefile, parent_id=folder_id, checksum=checksum)
  File "/usr/local/bin/gdcp", line 424, in upload_file
    status, response = request.next_chunk()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 867, in next_chunk
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 547, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1291, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```

**Comment by ctberthiaume** [comment]
This error will now restart the upload from scratch.
