### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by ohthetrees** [ctberthiaume/gdcp#12]
With gdcp version 0.7.2

Uploading a directory.
```
velvet.khmer.qc.name.fasta/SA_s13_150m_201505061430/Log
  100.00% 997 0.00MB/s 1.58s MD5...OK
velvet.khmer.qc.name.fasta/SA_s13_150m_201505061430/contigs.fa
  100.00% 132158880 30.17MB/s 4.38s MD5...OK
velvet.khmer.qc.name.fasta/SA_s13_150m_201505061430/stats.txt
  0.00% 0 0.00MB/s 0sTraceback (most recent call last):
  File "/usr/local/bin/gdcp", line 1216, in <module>
    main()
  File "/usr/local/bin/gdcp", line 1213, in main
    cli()
  File "/usr/local/bin/gdcp", line 1157, in cli
    args.func(args)
  File "/usr/local/bin/gdcp", line 1190, in cli_upload
    checksum=not args.no_checksum)
  File "/usr/local/bin/gdcp", line 82, in upload
    f.upload()
  File "/usr/local/bin/gdcp", line 161, in upload
    self.gdcp.upload(paths=allfiles, parent=self.id, checksum=self.check_checksum)
  File "/usr/local/bin/gdcp", line 82, in upload
    f.upload()
  File "/usr/local/bin/gdcp", line 161, in upload
    self.gdcp.upload(paths=allfiles, parent=self.id, checksum=self.check_checksum)
  File "/usr/local/bin/gdcp", line 82, in upload
    f.upload()
  File "/usr/local/bin/gdcp", line 194, in upload
    status, response = request.next_chunk()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 867, in next_chunk
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 547, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1258, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 833, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 803, in send
    datablock = data.read(blocksize)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 607, in read
    return self._stream.read(n)
IOError: [Errno 5] Input/output error
```

**Comment by ohthetrees** [comment]
I think this may have been s3fs weirdness.
