### ISSUE TITLE
KeyError: 'fileSize'

### ISSUE THREAD

**Issue by filmil** [ctberthiaume/gdcp#15]
First experience with gdcp, not that encouraging.

```
$ gdcp list
My Drive        0AFsJul7qtkQnUk9PVA     folder
My Drive/Backups        0B1sJul7qtkQnaHoyblFLSEFYZE0    folder
My Drive/Backup 0B1sJul7qtkQnUzE0Z3NPMzN2LTA    folder
Traceback (most recent call last):
  File "/home/f/local/bin/gdcp", line 1251, in <module>
    main()
  File "/home/f/local/bin/gdcp", line 1248, in main
    cli()
  File "/home/f/local/bin/gdcp", line 1194, in cli
    args.func(args)
  File "/home/f/local/bin/gdcp", line 1206, in cli_list
    gdcp.list(ids=ids, json_flag=args.json, depth=args.depth)
  File "/home/f/local/bin/gdcp", line 100, in list
    f.list(json_flag=json_flag, depth=depth)
  File "/home/f/local/bin/gdcp", line 394, in list
    c.list(json_flag, depth-1, new_pre)
  File "/home/f/local/bin/gdcp", line 396, in list
    self.print_file(json_flag, predecessors)
  File "/home/f/local/bin/gdcp", line 421, in print_file
    line.append(self.metadata["fileSize"])
KeyError: 'fileSize'
```

**Comment by ctberthiaume** [comment]
Thanks for reporting the bug. Files created with an app like Docs or Sheets were not handled correctly during listing. This should be resolved now.
