### ISSUE TITLE
ssl crash

### ISSUE THREAD

**Issue by ohthetrees** [ctberthiaume/gdcp#2]
```
01/15/2015 03:48:14 PM    INFO       gdcp                      : Uploaded 100.00%.  3202322094 bytes in 33m0.00s (1.58MB/s)
01/15/2015 03:48:14 PM    INFO       gdcp                      : Calculating MD5 checksum for /Old_3TB/Cedar/velvet/100819_Illumina/628HVAAXX_5_1.fastq
01/15/2015 04:29:53 PM    INFO       gdcp                      : MD5 OK.  c2bb21244112fed9aea01824a5f53ef8 (local) == c2bb21244112fed9aea01824a5f53ef8
01/15/2015 04:29:53 PM    INFO       gdcp                      : Uploading /Old_3TB/Cedar/velvet/100819_Illumina/628HVAAXX_5_2.fastq, mimeType=application/octet-stream
Traceback (most recent call last):
  File "/usr/local/bin/gdcp", line 941, in <module>
    main()
  File "/usr/local/bin/gdcp", line 38, in main
    cli()
  File "/usr/local/bin/gdcp", line 832, in cli
    args.func(args)
  File "/usr/local/bin/gdcp", line 897, in cli_upload_file
    not args.no_checksum)
  File "/usr/local/bin/gdcp", line 514, in upload_folder
    drive, subdir, parent_id=folder_id, checksum=checksum)
  File "/usr/local/bin/gdcp", line 514, in upload_folder
    drive, subdir, parent_id=folder_id, checksum=checksum)
  File "/usr/local/bin/gdcp", line 514, in upload_folder
    drive, subdir, parent_id=folder_id, checksum=checksum)
  File "/usr/local/bin/gdcp", line 509, in upload_folder
    drive, onefile, parent_id=folder_id, checksum=checksum)
  File "/usr/local/bin/gdcp", line 374, in upload_file
    status, response = request.next_chunk()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/googleapiclient/http.py", line 801, in next_chunk
    headers=start_headers)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauth2client/client.py", line 547, in new_request
    redirections, connection_type)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/httplib2/__init__.py", line 1300, in _conn_request
    conn.connect()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/httplib2/__init__.py", line 1021, in connect
    self.disable_ssl_certificate_validation, self.ca_certs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/httplib2/__init__.py", line 80, in _ssl_wrap_socket
    cert_reqs=cert_reqs, ca_certs=ca_certs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 392, in wrap_socket
    ciphers=ciphers)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 148, in __init__
    self.do_handshake()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
```

**Comment by ohthetrees** [comment]
Addressed by 67c1d48d27198fef9036873bc66e09cdb80bb5d3
