### ISSUE TITLE
error downloading google doc

### ISSUE THREAD

**Issue by ctberthiaume** [ctberthiaume/gdcp#3]
gdcp doesn't know how to download google doc files which should normally be converted to docx, xlsx, etc before download.  Here it was trying to download a Google Doc spreadsheet.  Google Docs have 0 file size in Google Drive which causes gdcp to crash.

```
Traceback (most recent call last):
  File "/Users/chrisbee/bin/gdcp", line 912, in <module>
    main()
  File "/Users/chrisbee/bin/gdcp", line 38, in main
    cli()
  File "/Users/chrisbee/bin/gdcp", line 804, in cli
    args.func(args)
  File "/Users/chrisbee/bin/gdcp", line 821, in cli_download_file
    failed = download_by_file_id(args.drive, args.id, not args.no_checksum, args.target)
  File "/Users/chrisbee/bin/gdcp", line 172, in download_by_file_id
    failed = download_file(drive, downfile, checksum=checksum, root=root)
  File "/Users/chrisbee/bin/gdcp", line 190, in download_file
    drive, onefile, checksum=checksum, root=folder_path)
  File "/Users/chrisbee/bin/gdcp", line 195, in download_file
    file_size = int(afile["fileSize"])
  File "/Users/chrisbee/Library/Python/2.7/lib/python/site-packages/pydrive/files.py", line 113, in __getitem__
    raise KeyError(e)
KeyError: KeyError('fileSize',)
```

**Comment by ohthetrees** [comment]
It it an option to download a clickable shortcut document as the desktop client does? For example a google doc that I have shows up in the google client as: `foo.gdoc`

with contents of:
```
{"url": "https://docs.google.com/open?id=1NZbndlDYe5Xqq8WQXtkOJEFZx8q1OhTAZFnI0pozjvU", "doc_id": "1NZbndlDYe5Xqq8WQXtkOJEFZx8q1OhTAZFnI0pozjvU", "email": "cmckay@uw.edu", "resource_id": "document:1NZbndlDYe5Xqq8WQXtkOJEFZx8q1OhTAZFnI0pozjvU"}
```

The appeal to me is that you don't have all these magic copies of google docs, when maybe what you want is the google doc. If we wanted a docx, we'd have put a docx in gdrive.

**Comment by ctberthiaume** [comment]
For now I'm skipping Google Docs in downloads so that they don't throw an error, but eventually we could download them as JSON files like the Drive sync client does.
