### ISSUE TITLE
missing file crash

### ISSUE THREAD

**Issue by ohthetrees** [ctberthiaume/gdcp#6]
gdcp doesn't like it when you delete a file out from underneath it. 

This may best be filed under "won't fix".

This time it failed while checking the checksum, but I'm sure it would have been ugly during the upload too. 

```
01/23/2015 08:11:18 PM    INFO       gdcp                      : Uploading /Old_3TB/Cedar/xtandem/7_protein/P1F3D2000.proph_FVAL_4.png, mimeType=image/png
01/23/2015 08:11:19 PM    INFO       gdcp                      : Uploaded 100.00%.  2875 bytes in 1.12s (0.00MB/s)
01/23/2015 08:11:19 PM    INFO       gdcp                      : Calculating MD5 checksum for /Old_3TB/Cedar/xtandem/7_protein/P1F3D2000.proph_FVAL_4.png
Traceback (most recent call last):
  File "/usr/local/bin/gdcp", line 998, in <module>
    main()
  File "/usr/local/bin/gdcp", line 39, in main
    cli()
  File "/usr/local/bin/gdcp", line 889, in cli
    args.func(args)
  File "/usr/local/bin/gdcp", line 954, in cli_upload_file
    not args.no_checksum)
  File "/usr/local/bin/gdcp", line 571, in upload_folder
    drive, subdir, parent_id=folder_id, checksum=checksum)
  File "/usr/local/bin/gdcp", line 571, in upload_folder
    drive, subdir, parent_id=folder_id, checksum=checksum)
  File "/usr/local/bin/gdcp", line 571, in upload_folder
    drive, subdir, parent_id=folder_id, checksum=checksum)
  File "/usr/local/bin/gdcp", line 566, in upload_folder
    drive, onefile, parent_id=folder_id, checksum=checksum)
  File "/usr/local/bin/gdcp", line 537, in upload_file
    if not check_md5(file_path, response["md5Checksum"]):
  File "/usr/local/bin/gdcp", line 634, in check_md5
    output.rstrip())
UnboundLocalError: local variable 'output' referenced before assignment
```

**Comment by ctberthiaume** [comment]
I think it's OK to leave this one unfixed for now. You can delete files within a directory tree that's being uploaded, just not ones that are at the same level as the directory being processed during some recursive traversal. So these kinds of errors (file deleted during processing) won't come up too often I think, and it should be obvious which file deletion caused the error when they occur.
